//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace weather.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("weather.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7STV {
            get {
                object obj = ResourceManager.GetObject("_7STV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bez_imeni_1 {
            get {
                object obj = ResourceManager.GetObject("Bez_imeni_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap c3 {
            get {
                object obj = ResourceManager.GetObject("c3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap c3_st {
            get {
                object obj = ResourceManager.GetObject("c3_st", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В постсоветский период в 1990-е годы моногород испытал стагнацию в связи с общим для страны упадком промышленности, а также крупным пожаром с полным разрушением завода двигателей КАМАЗа 1993 года. Это сопровождалось разгулом преступности (которая была довольно высока еще в 80-е годы) и подъёмом татарского национализма.
        ///В 2000-х годах началось оживление производств и новое развитие города. Появляются новые здания и целые микрорайоны — Радужный, Яшьлек, Замелекесье, Прибрежный и т. д. В значительной мере воз [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Chelny {
            get {
                return ResourceManager.GetString("Chelny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clear {
            get {
                object obj = ResourceManager.GetObject("clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CZk {
            get {
                object obj = ResourceManager.GetObject("CZk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d {
            get {
                object obj = ResourceManager.GetObject("d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d_c1 {
            get {
                object obj = ResourceManager.GetObject("d_c1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d_c2 {
            get {
                object obj = ResourceManager.GetObject("d_c2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap D1 {
            get {
                object obj = ResourceManager.GetObject("D1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название город получил от реки Детройт (фр. le détroit du Lac Érie), которое означает пролив озера Эри, соединяющий озеро Гурон с озером Эри. В XVII—XVIII вв. под проливом понимали не только нынешнюю реку Детройт, но и озеро Сен-Клер и одноимённую реку. Путешествуя вверх по реке Детройт на корабле Ла Саля, католический священник Луи Хеннепин отметил, что северный берег идеально подходит для поселения. Здесь в 1701 году Антуан Ломе де Ла Мот-Кадильяк (фр. Antoine Laumet de La Mothe, sieur de Cadillac) с груп [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Detroit {
            get {
                return ResourceManager.GetString("Detroit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fyCe {
            get {
                object obj = ResourceManager.GetObject("fyCe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GXHc {
            get {
                object obj = ResourceManager.GetObject("GXHc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap irkut {
            get {
                object obj = ResourceManager.GetObject("irkut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Древнейшие следы пребывания человека на территории Иркутска датируются возрастом около 50 тысяч лет.
        /// Поселения и могильники, относящиеся к каменному, бронзовому и железному векам, обнаружены на обоих берегах Ангары (стоянки Военный госпиталь, им. Арембовского, Щапова I—III, Переселенческий Пункт, им. Герасимова, Мамоны II.
        /// Верхоленская гора, Роща «Звездочка», Царь-Девица, Титово, Лисиха, Кузьмиха, Иркутск-мост (левый берег), Глазковская церковь, могильники неолитической китойской культуры (некрополи Гла [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Irkutsk {
            get {
                return ResourceManager.GetString("Irkutsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kaz {
            get {
                object obj = ResourceManager.GetObject("kaz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В августе 1628 года Андреем Дубенским был основан Красноярск. Острог был построен с 6 августа по 18 августа 1628 года. По вершинам окружающих котловину гор создана круговая караульная служба.
        ///
        ///До второй половины XVII века Красноярск был под ведомством разрядного города Томска, а затем разрядного Енисейска.
        ///
        ///В 1635 году в Красноярске организована конная сотня.
        ///
        ///Набеги киргизских князей на Красноярск совершались в 1630, 1634, 1636, 1640, 1665, 1667 и 1679 годах. 1679 год — осада объединённых войск енисе [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Krasn1 {
            get {
                return ResourceManager.GetString("Krasn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap krasnoyarsk {
            get {
                object obj = ResourceManager.GetObject("krasnoyarsk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В XX веке город ожидали большие потрясения. Казань стала одним из центров революции. 2 марта 1917 года в Казани был образован городской Совет рабочих и солдатских депутатов, была упразднена власть губернатора, чьи полномочия были переданы губернскому комиссару.
        ///
        ///В 1918 году за город в ходе гражданской войны велись ожесточённые бои, в том числе за оказавшийся в городе и затем пропавший золотой запас царской России. Войска чехословацкого корпуса в ходе пятидневных боев взяли Казань 6 августа, а красные выби [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string KZ {
            get {
                return ResourceManager.GetString("KZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В XVIII веке для обслуживания 2-й Камчатской экспедиции Витуса Беринга была открыта ямская почтовая станция Мухтуя.
        ///
        ///В XIX — начале XX века Мухтуя была местом политической ссылки.
        ///
        ///Стремительный рост города начался с середины XX века, и связан с открытием и разработкой алмазных месторождений в бассейне Вилюя. Поскольку посёлок был ближайшим (230 км) населённым пунктом к кимберлитовой трубке «Мир», то он стал «базой» для строительства города Мирного. В 1956 году от Мухтуи к будущему Мирному началась прок [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Len1 {
            get {
                return ResourceManager.GetString("Len1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lensk {
            get {
                object obj = ResourceManager.GetObject("lensk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лондона — крупнейшего города и столицы Великобритании — насчитывает, по крайней мере, 1970 лет. Согласно легенде, Лондон был основан Брутом Троянским и назван Troia Nova (с латыни Новая Троя). Однако это предание не подтверждается археологическими раскопками, и считается, что Лондон основали римляне в 43 году н. э.
        ///
        ///Изначально это было небольшое поселение площадью около 0,8 км2. К 100 году Лондон стал столицей Британии и во II веке достиг своего расцвета. После ухода римлян Лондон был заброшен и пришёл в  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string London {
            get {
                return ResourceManager.GetString("London", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap London1 {
            get {
                object obj = ResourceManager.GetObject("London1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mist {
            get {
                object obj = ResourceManager.GetObject("mist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В 1947 году было масштабно отпраздновано 800-летие Москвы, но отпраздновано в сентябре, а не 4 апреля как по Ипатьевской летописи.
        ///
        ///
        ///Строительство Новоарбатского моста, 1957 год
        ///В 1952—1957 годах было проведено строительство высотных зданий, впоследствии получивших название «Сталинских высоток» и ставших одним из символов Москвы советской эпохи.
        ///
        ///Зимой 1959—1960 годов в Москве произошла вспышка чёрной оспы, которую привёз из Индии известный художник, дважды лауреат Сталинской премии Алексей Кокорекин, [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string MS {
            get {
                return ResourceManager.GetString("MS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MSK {
            get {
                object obj = ResourceManager.GetObject("MSK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap n {
            get {
                object obj = ResourceManager.GetObject("n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap n_c1 {
            get {
                object obj = ResourceManager.GetObject("n_c1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap n4V {
            get {
                object obj = ResourceManager.GetObject("n4V", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nab {
            get {
                object obj = ResourceManager.GetObject("nab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap new_york {
            get {
                object obj = ResourceManager.GetObject("new_york", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на До европейцев на этой территории были поселения коренных жителей, индейцев — племён делаваров и метоаков. Французский мореплаватель итальянского происхождения Джованни да Верраццано, который назвал это место Нувель Ангулем (фр. Nouvelle-Angoulême), доплыл до залива Нью-Йорка в 1524 году, но колония не была основана.
        ///
        ///Подлинная история города начинается с голландских поисков быстрого пути в Азию. Генри Гудзон, англичанин на службе Голландской Ост-Индской компании, который искал выход в Тихий океан, в 1609  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string New_Yourt {
            get {
                return ResourceManager.GetString("New_Yourt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nijnii {
            get {
                object obj = ResourceManager.GetObject("Nijnii", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нижний Новгород был основан князем Юрием Всеволодовичем в 1221 году. Его жители, под предводительством старосты Кузьмы Минина и князя Дмитрия Пожарского, собрали ополчение для освобождения Москвы от польских захватчиков в 1611 году. Город был главным международным торговым центром России с 1817 года. В советский период был переименован в Горький, в честь писателя Максима Горького, и являлся закрытым индустриальным городом Советского Союза. Во время Великой Отечественной войны, на протяжении трёх лет, подвер [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string nizhnyy1 {
            get {
                return ResourceManager.GetString("nizhnyy1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нори́льск — город краевого подчинения Красноярского края. Расположен на севере региона к югу от Таймырского полуострова, примерно в 90 км к востоку от Енисея и в 1500 км севернее Красноярска, в 300 км к северу от Северного полярного круга, и в 2400 км от Северного полюса.
        ///
        ///Норильск — самый северный город России с численностью населения более 150 тысяч человек.
        ///
        ///В 2004 году два города-спутника (Талнах, Кайеркан) стали районами города Норильска, а Оганер — пригородом Центрального района. Норильску подчинё [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Noril1 {
            get {
                return ResourceManager.GetString("Noril1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap norilsk {
            get {
                object obj = ResourceManager.GetObject("norilsk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В начале XX века Кузнецк по-прежнему оставался захолустным уездным городом. Строительство Транссиба мало затронуло удаленный от него Кузнецк и Кузнецкий уезд. Удаленность Кузнецка от основных путей сообщения и отсутствие крупной промышленности фабрично-заводского типа привело к тому, что большая часть горожан все ещё было связана с сельским хозяйством. Сельское хозяйство носило полунатуральный характер. Мелкая промышленность и ремесленно-промысловая деятельность превалировала над торговлей и казенной службо [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string NovKyz1 {
            get {
                return ResourceManager.GetString("NovKyz1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Novokyz {
            get {
                object obj = ResourceManager.GetObject("Novokyz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Считается, что первые люди обосновались в окрестностях Новороссийска ещё в эпоху палеолита. В V в. до н. э. на месте современного Новороссийска возник Бата — торговый греческий город. Во II веке до н. э. он разрушен кочевниками-аланами. В XIII веке в устье реки Цемес генуэзцами была построена крепость Батарио. В 1453 году турки-османы взяли штурмом Константинополь, Тамань и Цемесская бухта перешли в турецкие владения. В XVIII веке на территории будущего Новороссийска находилась турецкая крепость Суджук-кале [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string NOVOR1 {
            get {
                return ResourceManager.GetString("NOVOR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Novosibirsk {
            get {
                object obj = ResourceManager.GetObject("Novosibirsk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В 1804 году экспедиция Льюиса и Кларка исследовала берега реки Миссури и общалась с местными племенами. На месте встречи экспедиции с вождями индейцев в 1819 году был построен форт Аткинсон, а в 1822 году рядом с ним появилась торговая фактория Американской пушной компании. В 1846 году вблизи современной Омахи пролегала Мормонская тропа, по которой мормоны двигались на запад после своего изгнания из Иллинойса. С разрешения племени омаха они перезимовали в Небраске.
        ///
        ///В начале 1850-х годов территорию Омахи  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string omaha {
            get {
                return ResourceManager.GetString("omaha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap omaha1 {
            get {
                object obj = ResourceManager.GetObject("omaha1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap omsk {
            get {
                object obj = ResourceManager.GetObject("omsk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В каменном веке биологическая и климатическая обстановка на омской земле была сходной с современной, однако реки Иртыш, Омь, Замарайка и Камышловка были богаты рыбой, а в приобрежных районах водилось множество копытных и птиц. Затем здесь поселились люди, за тысячелетия образовав комплекс археологических памятников Омской стоянки.
        ///
        ///Первые поселенцы пришли сюда в VI тысячелетии до н. э. и разместились в районе устья реки Замарайки, левого притока Иртыша. Они принадлежали к европеоидно-монголоидной расе и б [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Omsk1 {
            get {
                return ResourceManager.GetString("Omsk1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Samara {
            get {
                object obj = ResourceManager.GetObject("Samara", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В западноевропейских источниках информация о Средней Азии до третьей четверти XII века отсутствует. Сведения о Средней и Центральной Азии появляются в Европе в связи с фигурой пресвитера Иоанна и его «письмом», которое датируется около 1165 (до 1177) года.
        ///
        ///Одним из ранних документов, где встречается упоминание топонима, является «Хроника» (лат. Chronicon, датируемая 1130/1131—1135 гг. Гуго Сен-Викторского, одного из основателей Сен-Викторской теологической школы богословия XII столетия. «Хроника» предста [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Samara1 {
            get {
                return ResourceManager.GetString("Samara1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Энсо был основан в кунте Яаски Выборгской губернии в 1887 году, когда барон Ади Стандершкёльд (1855—1935), сын Карла Августа Стандершкёльда (швед. Carl August Standertskjöld, 1814—1885), выкупил у водопада Ряйккёля (фин. Räikkölä) на реке Вуоксе 16 гектаров земли[6]. Он построил на них завод древесной массы. Вокруг предприятия был построен посёлок, которому барон дал название Э́нсо (фин. Enso, «первенец»). Позже завод был расширен до картонно-бумажной фабрики (энсовский комбинат или завод «Энсо»). Это было  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Svet1 {
            get {
                return ResourceManager.GetString("Svet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap svetogorsk {
            get {
                object obj = ResourceManager.GetObject("svetogorsk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tomsk {
            get {
                object obj = ResourceManager.GetObject("Tomsk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 20 января 1604 года в Москву ко двору Бориса Годунова приехало посольство во главе с князем эуштинских татар Тояном с просьбой о принятии их под власть Русского царства и о возведении на реке Томи острога для защиты эуштинцев от нападений воинственных соседей — енисейских кыргызов и калмыков. 25 марта 1604 года Борис Годунов послал казачьего голову Гаврилу Писемского из Сургута и стрелецкого голову Василия Тыркова из Тобольска с заданием основать город на берегу реки Томи, в татарской земле, завести вокруг  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string tomsk1 {
            get {
                return ResourceManager.GetString("tomsk1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на крупнейший город Канады, административный центр провинции Онтарио. Население — 2 731 571 чел. (2016); вместе с городами Миссиссога, Брамптон, Маркем и другими образует агломерацию Большой Торонто с населением 5928 тыс. жителей.
        ///
        ///Торонто является частью «золотой подковы» — густонаселённого региона вокруг западной части озера Онтарио с населением около 7 млн человек. Приблизительно одна треть всего населения Канады живёт в радиусе 500 км от Торонто. Около шестой части всех рабочих мест Канады находятся в пр [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Toronto {
            get {
                return ResourceManager.GetString("Toronto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toronto1 {
            get {
                object obj = ResourceManager.GetObject("toronto1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap totoro {
            get {
                object obj = ResourceManager.GetObject("totoro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О том, что в Печорском крае имеется «огненный камень», было известно давно. Первыми учеными, которые находили уголь в этих краях, были Т. А. Борноволоков (1809 г.), А. Деньгин (1828 г.), А. А. Кейзерлинг (1843 г.), Э. К. Гофман (1847 г.) и др., а первым предпринимателем, который ещё в XIX веке (1867 год) хотел поставить богатства Севера на службу человека, был русский промышленник М. К. Сидоров, но в то время на это не имелось средств. Север требовал и требует немалых вложений в своё развитие.
        ///
        ///Позднее по [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Vorkuta {
            get {
                return ResourceManager.GetString("Vorkuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vorkuta1 {
            get {
                object obj = ResourceManager.GetObject("vorkuta1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
